#pragma link C++ class EventManager-!;
#pragma link C++ class JetProxyBuilder<nanoaod::Jet>-!;
#pragma link C++ class JetProxyBuilder<nanoaod::CaloJet>-!;
#pragma link C++ class ElectronProxyBuilder<nanoaod::Electron>-!;
#pragma link C++ class ElectronProxyBuilder<nanoaod::Tau>-!;
#pragma link C++ class MuonProxyBuilder-!;
#pragma link C++ class VertexProxyBuilder-!;
#pragma link C++ class METProxyBuilder<nanoaod::MET>-!;
#pragma link C++ class METProxyBuilder<nanoaod::CaloMET>-!;